modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/InternalErrorGit/BetterFactories/issues"
[[mods]]
modId="betterfactories"
version="${file.jarVersion}"
displayName="BetterFactories"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/InternalErrorGit/BetterFactories"
#logoFile="BetterFactories.png"
#credits="Thanks for this example mod goes to Java"
authors="InternalError_"
description='''

'''
[[dependencies.betterfactories]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterfactories]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
